### ISSUE TITLE
Returned features max is 1000 ?

### ISSUE THREAD

**Issue by nouryf** [CrunchyData/pg_featureserv#106]
I followed the steps to setup Boston routing example as outlined in https://github.com/CrunchyData/pg_featureserv/blob/master/examples/openlayers/openlayers-pgrouting.md

The example worked just fine. However when trying to view the features of the PG tables generated using osm2pgrouting, i got unexpected results:

Table "ways" has a count of 20883 rows:
```
routing=# select count(*) from ways;
 count
-------
 20883
(1 row)
```

After starting the feature_serv and using the browser to view the "ways" table using 50000 max features, I got back only 1000.

Here is the debug output after executing in the browser: `http://localhost:9000/collections/public.ways/items.html?limit=30000`

`INFO[1038] [::1]:36266 GET /collections/public.ways/items.html?limit=30000
DEBU[1038] ---- Request complete in 538.8µs
INFO[1039] [::1]:36266 GET /collections/public.ways/items.json?limit=30000
DEBU[1039] Features query: SELECT ST_AsGeoJSON( "the_geom"  ) AS _geojson , "gid","osm_id","tag_id","length","length_m","name"::text,"source","target","source_osm","target_osm","cost","reverse_cost","cost_s","reverse_cost_s","rule"::text,"one_way","oneway"::text,"x1","y1","x2","y2","maxspeed_forward","maxspeed_backward","priority" FROM "public"."ways"    LIMIT 1000;
DEBU[1039] Database query result: 1000 rows in 23.8272ms
DEBU[1039] ---- Request complete in 46.5746ms`

The request pass the correct limit of 30000 but some how the SQL request that got executed in the back end has in it "LIMIT 1000".

Was that done in purpose and its a throttling parameter some where that can be overridden ? or this is simply a bug ?

Thanks

**Comment by nouryf** [comment]
It looks like this can be overridden through **./config/pg_featureserv.toml** using **LimitMax** value. So this is definitively not a bug just a configuration thing.

**Comment by dr-jts** [comment]
Yes, the maximum limit is configurable.  Good that you found it.

**Comment by dBitech** [comment]
it may be worth mentioning in the docs, that the config file LimitMax will place an upper bound on the Limit as passed in via the URI.

**Comment by dr-jts** [comment]
It is mentioned in the [Configuration doc](https://access.crunchydata.com/documentation/pg_featureserv/latest/installation/configuration/).

I guess it could also be mentioned in the `limit` parameter doc, and in the Troubleshooting section.
