### ISSUE TITLE
Attribute filter containing % not working?

### ISSUE THREAD

**Issue by KoalaGeo** [CrunchyData/pg_featureserv#111]
Hi, 

Minor error in URL encoding from HTML to JSON response

If filtering using wildcard % such as:
http://XXXX/collections/landslides.bedrock_geology/items?f=json&lang=en-US&properties=fid,geom,LEX,LEX_RCS,RCS,RCS_X,RCS_D,RANK&limit=100&LEX=UI% 

![image](https://user-images.githubusercontent.com/33657876/172126384-447f65f1-9ef7-4959-8bd4-88b0c6aff115.png)

When you click to get the JSON response pg_featureserv appends "25" to the URL path such as below which has zero responses: 
http://XXXX/collections/landslides.bedrock_geology/items.json?f=json&lang=en-US&properties=fid,geom,LEX,LEX_RCS,RCS,RCS_X,RCS_D,RANK&limit=100&LEX=UI%25

Entering the URL manually then all features are returned correctly - http://XXXX/collections/landslides.bedrock_geology/items.json?f=json&lang=en-US&properties=fid,geom,LEX,LEX_RCS,RCS,RCS_X,RCS_D,RANK&limit=100&LEX=UI%

**Comment by dr-jts** [comment]
The JSON link in the response page is URL-encoded, so the "%" is encoded as `%25`.  This is decoded when the request is submitted to produce the desired "UI%" attribute filter query value.

Attribute filters don't support wildcards, so the "%" is interpreted as an actual value, not a database wildcard. 

To use wildcard value queries you need to use `LIKE` or `ILIKE` in a CQL expression (see [doc](https://github.com/CrunchyData/pg_featureserv/blob/master/hugo/content/usage/cql.md#like-predicate)).
