### ISSUE TITLE
Tagging Docker releases?

### ISSUE THREAD

**Issue by gamesbook** [CrunchyData/pg_featureserv#118]
I really appreciate having pre-built Docker releases available on DockerHub (https://hub.docker.com/r/pramsey/pg_featureserv/).

However, is it possible to create tagged versions - not just "latest" - so that we can manage upgrades in a more systematic way?

Thanks!

**Comment by RoryMMMM** [comment]
I would also appreciate this being implemented... It makes it a little tough to know which "latest" my server is running on.
