### ISSUE TITLE
Tables/Views aren't picked up if Geometry Type isn't declared? 

### ISSUE THREAD

**Issue by KoalaGeo** [CrunchyData/pg_featureserv#135]
Hi @pramsey, 

Testing pg_featureserv & tileserv, noticed some tables aren't coming through to the API. 

Common factor appear to be where:
Data type: `geometry`
Where geometries include both `Polygon` & `MultiPolygon` in the same table/view

Tables/views which do work:
Data type: `geometry(point, 4326)` or `geometry(polygon, 4326)` or `geometry(polyline, 4326)`
& the geometries are all one type. 

Is this expected behaviour? 

The tables/views with mixed geometry types don't seem to be an issue for other ogcapi servers like pygeoapi.

**Comment by dr-jts** [comment]
Mixe-type geometry should not be a problem. But the geometry definition needs to include an explicit SRID.

**Comment by KoalaGeo** [comment]
So I need to do a `:: geometry (4326) as shape` and it should work?

**Comment by dr-jts** [comment]
Should do.  Try it, and please report back it it doesn't work.

**Comment by KoalaGeo** [comment]
Unfortunately, using `::geometry(4326) as shape` is giving me 
```
SQL Error [22023]: ERROR: Invalid geometry type modifier: 4326
  Position: 1094
```

My SQL originally looks like:
```
CREATE MATERIALIZED VIEW published.ql_cmd_cruise_layer_web
TABLESPACE pg_default
AS SELECT ql_cmd_cruise_layer_web.cruise_id,
    ql_cmd_cruise_layer_web.cruise,
    ql_cmd_cruise_layer_web.shape_wgs84::geometry AS shape_wgs84,
    ql_cmd_cruise_layer_web.cruise_data_url
   FROM oracle_fdw.ql_cmd_cruise_layer_web
WITH DATA;
```

Any suggestions? Do I need to use something like `UpdateGeometrySRID`?

**Comment by KoalaGeo** [comment]
Fixed it thanks to https://stackoverflow.com/a/75821730/13272123 - it's possible to use the generic geometry type during the cast

`ql_cmd_cruise_layer_web.shape_wgs84::geometry(geometry,4326) AS shape_wgs84, `

**Comment by pramsey** [comment]
Cool. By way of explanation, this gives us the information we need to do automatic reprojection from the database projection to the MVT projection.

**Comment by dr-jts** [comment]
> this gives us the information we need to do automatic reprojection from the database projection to the MVT projection.

.. and to the geodetic coordinate system which is the default for GeoJSON ;)
