### ISSUE TITLE
Used libraries `gorilla/mux` and `gorilla/handlers` became archived

### ISSUE THREAD

**Issue by JakobMiksch** [CrunchyData/pg_featureserv#136]
The libraries https://github.com/gorilla/mux and https://github.com/gorilla/handlers became archived It would be good to replace them at one point in `pg_featureserv`

**Comment by dr-jts** [comment]
Agreed.  Thanks for pointing this out.  Any ideas on a suitable replacement?

**Comment by JakobMiksch** [comment]
I cannot make a recommendation regarding a replacement. Maybe this list is helpful: https://awesome-go.com/routers/

**Comment by sander-su** [comment]
https://github.com/mingrammer/go-web-framework-stars
we use gin

**Comment by JakobMiksch** [comment]
closing because library is revived https://gorilla.github.io/blog/2023-07-17-project-status-update/
