### ISSUE TITLE
CQL Temporal filter possible? 

### ISSUE THREAD

**Issue by KoalaGeo** [CrunchyData/pg_featureserv#138]
Hi, 

I trying to serve some sensor data and need to be able to do some temporal CQL filtering, `AFTER`, `BETWEEN` etc. 

I'm not clear if this is supported in pg_featureserv yet? 

The datatype is listed as "string"....
![image](https://github.com/CrunchyData/pg_featureserv/assets/33657876/1bd2ae7c-6956-45c6-b06a-2f4b9111040a)

JSON response is showing as 
![image](https://github.com/CrunchyData/pg_featureserv/assets/33657876/907f0c9c-f85c-4475-8d8e-6a5a9c37a3c9)

If run a query like `http://pg-featureserv-2309-master.kube-idev.bgslcdevops.test/collections/published.ql_sen_water_level_data_sta/items.json?https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&filter=resulttime%20AFTER%202022-09-17T00:00:00Z` 

I get:
`CQL syntax error: "resulttime  !!>> AFTER 2022-09-17T00:00:00Z"`

Any ideas?

**Comment by KoalaGeo** [comment]
Found the answer - https://github.com/CrunchyData/pg_featureserv/blob/master/hugo/content/usage/cql.md#temporal-filters

For some reason this doc isn't being included in the docs at https://access.crunchydata.com/documentation/pg_featureserv/latest/usage/

**Comment by dr-jts** [comment]
Yes, we need to update the online doco.  Good that you found the answer.
