### ISSUE TITLE
exponential numbers in cql filter are not parsed

### ISSUE THREAD

**Issue by simonseyock** [CrunchyData/pg_featureserv#141]
I don't know exactly if this is malformed WKT, but as it was produced by OpenLayers and is accepted by PostGIS directly, I assume this is an error in the CQL parser.

The problem occurs with exponential numbers like `1.3969838619232178e-9`.

The CQL is:
```
INTERSECTS(geom, POLYGON((-2504688.542848654 2504688.542848654,-2504688.542848654 5009377.08569731,1.3969838619232178e-9 5009377.08569731,1.3969838619232178e-9 2504688.542848654,-2504688.542848654 2504688.542848654)))
```

The error is:
```
CQL syntax error: "...1,1.3969838619232178 !!>> e-9 5009377.08569731..."
```

The same WKT is parsed in PostGIS correctly:
```sql
select st_geomfromtext('POLYGON((-2504688.542848654 2504688.542848654, -2504688.542848654 5009377.08569731, 1.3969838619232178e-9 5009377.08569731, 1.3969838619232178e-9 2504688.542848654, -2504688.542848654 2504688.542848654))', 3857)
```

**Comment by dr-jts** [comment]
It looks like the CQL parser only accepts exponential notation using upper-case `E` ([code](https://github.com/CrunchyData/pg_featureserv/blob/master/internal/cql/CqlLexer.g4#L170)).

This should be an easy fix.

**Comment by dr-jts** [comment]
Fixed in https://github.com/CrunchyData/pg_featureserv/commit/82fab99ea2f3594cccccf72a94da5cb4bb036385
