### ISSUE TITLE
Trying to use bbox with a custom function is throwing errors

### ISSUE THREAD

**Issue by jjhi11** [CrunchyData/pg_featureserv#157]
I have this custom exposed function that I would like to use the bbox option for. When i pass the coordinates through I get this error. 

Error scanning rows for Features: ERROR: ST_Intersects: Operation on mixed SRID geometries (Polygon, 3857) != (Polygon, 4326) (SQLSTATE XX000)

It works when I use the collection url with a bbox parameter.

I tried using the bbox-crs= parameter with no luck.

Here is the [URL](https://pgfeatureserv-souochdo6a-wm.a.run.app/functions/postgisftw.query_unit_age/items.json?unit_age_pattern=jurassic%25&tolerance=1&limit=1000&bbox=-114.4774,36.8855,-109.2498,39.7067)

**Comment by dr-jts** [comment]
Can you provide the table definition for the underlying table?

**Comment by jjhi11** [comment]
![Screenshot 2024-01-25 at 5 29 13 PM](https://github.com/CrunchyData/pg_featureserv/assets/27784116/8c910152-59f4-45e3-83e8-bb3ea2cb0afd)

**Comment by dr-jts** [comment]
Are you converting the table geometry to 4326 in the function?  If not, can you try that?

**Comment by jjhi11** [comment]
That seems to have fixed the issue! Was I using the bbox-crs parameter wrong? Thanks for the help!
