### ISSUE TITLE
Distinguish between "BindHost" and "UrlBase"

### ISSUE THREAD

**Issue by pramsey** [CrunchyData/pg_featureserv#16]
From my reading the "BindHost", the network interface to which the HTTP service is binding, is also being used as the URL base in the generated links in various API docs. These two concepts need to be separated.

The BindHost is where the server attaches. It should really be a netmask, like "0.0.0.0" to allow binding on all addresses. The current default, "localhost" (aka "127.0.0.1") means that the service binds to localhost and *only accepts requests* on localhost. This seems to actually break container running in my case (see https://stackoverflow.com/a/44099800/429821)

The BaseURL is the thing that goes in front of all the links in JSON, to convert them from relative links to fully qualified links (too bad service standards don't say things about resolving relative links... anyways). The best thing (I think) to do for the BaseURL is to figure out where the requester *thinks* they are calling, and use that in the returned value. See my utility function here: https://github.com/CrunchyData/pg_tileserv/blob/master/util.go#L23

Finally, in case the automatic lookup of BaseURL fails, leave the option for configuration to be set to force it to a particular value.

**Comment by dr-jts** [comment]
Closed by #18
