### ISSUE TITLE
CQL filter fails when more than 2 conditions

### ISSUE THREAD

**Issue by sebakerckhof** [CrunchyData/pg_featureserv#162]
I'm trying to add a CQL filter which needs to check 3 conditions, so something like:
`foo > 1 AND bar < 10 AND INTERSECTS(geom, ENVELOPE(0,1,2,3))`

But I get a syntax error: `CQL syntax error: "...bar <10)  !!>> AND INTERSECTS(geom..."`

If I try with only 2 conditions (any 2 out of 3), it works fine.
So I'm guessing something is wrong with the CQL parser when provided with more than 2 conditions.

**Comment by sebakerckhof** [comment]
Update: had a look at the parsers, and apparently it requires additional parenthesis, so
`(foo > 1 AND bar < 10) AND INTERSECTS(geom, ENVELOPE(0,1,2,3))` will work.

**Comment by dr-jts** [comment]
Well that turned to be harder than I though. But I learned some helpful things about ANTLR4 along the way.

Fixed by https://github.com/CrunchyData/pg_featureserv/commit/a0d25e3bc0e829445039798134ff8c59862a6fc6

**Comment by sebakerckhof** [comment]
Thanks for the quick fix!
