### ISSUE TITLE
Can't select case sensitive `properties` as URL parameter

### ISSUE THREAD

**Issue by KiwiKilian** [CrunchyData/pg_featureserv#166]
We have camelCased properties, e.g. `otherField`. These properties will be included as expected in the response when **not** setting the `properties` parameter. The properties are also properly listed in the table on the collections site.

But with a URL query like `&properties=field,otherField` only the the property `field` will be within `properties` – `otherField` is missing.

**Comment by dr-jts** [comment]
Fixed by https://github.com/CrunchyData/pg_featureserv/commit/5a6a10c3591e67d39b27b31d866db934b5e1a06a
