### ISSUE TITLE
Data not being returned in correct order with "Offset" and "Limit"

### ISSUE THREAD

**Issue by RoryMMMM** [CrunchyData/pg_featureserv#169]
I have a materialised view of data that is being shared using PG-Featureserv. My SQL looks like: 

```
CREATE MATERIALIZED VIEW IF NOT EXISTS postgisftw.hex_environmental_features_30m
TABLESPACE pg_default
AS
SELECT 
	row_number() OVER () AS id,
	hex_grid.gid as gid,
	hex_grid.geom::geometry(Polygon,4326) as geom,
	canopy_hex_summary.mean as canopy_mean,
	canopy_hex_summary.max as canopy_max,
	canopy_hex_summary.min as canopy_min,
	canopy_hex_summary.stddev as canopy_stddev,

	surface_hex_summary.mean as surface_mean,
	surface_hex_summary.max as surface_max,
	surface_hex_summary.min as surface_min,
	surface_hex_summary.stddev as surface_stddev,

	built_area_hex_summary.built_area,
	asphalt_length_hex_summary.asphalt_length,
	highway_length_hex_summary.highway_length,
	population_hex_summary.pop_total
 
FROM geo.hex_grid
LEFT JOIN geo.canopy_hex_summary               ON hex_grid.gid = canopy_hex_summary.gid
LEFT JOIN geo.surface_hex_summary               ON hex_grid.gid = surface_hex_summary.gid
LEFT JOIN osm.built_area_hex_summary          ON hex_grid.gid = built_area_hex_summary.gid
LEFT JOIN osm.asphalt_length_hex_summary  ON hex_grid.gid = asphalt_length_hex_summary.gid
LEFT JOIN osm.highway_length_hex_summary ON hex_grid.gid = highway_length_hex_summary.gid
LEFT JOIN pop.population_hex_summary          ON hex_grid.gid = population_hex_summary.gid
ORDER BY gid
WITH DATA;
```
 Where this is all just a bunch of raster and vector data being aggregated over a hexagonal grid. There are about 150 thousand grid cells and my default limit is to return max 10k rows. To get the complete dataset requires ~15 queries. 

I'm trying to pull this data into Python to do some ML work. The issue is that I'm receiving duplicate rows (and possibly missing rows too) and it seems to be due to not receiving the data in order. The following URL returns different values each time it is run: 
```
http://localhost:9999/collections/postgisftw.hex_environmental_features_30m/items.json?limit=1&offset=10000
```
Downloading the whole table with PGAdmin contains no duplicates. 

I'm using docker for everything and running the current latest version: pramsey/pg_featureserv:latest
Postgres version is: PostgreSQL 16.1 (Ubuntu 16.1-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

Is this a bug or am I doing it wrong? Is there a way to ensure that I'm downloading the entire collection using multiple queries?

**Comment by dr-jts** [comment]
Since the materialized view contains an `ORDER BY`, it seems like it should present the data in order to a query.  `pg_featureserv` should just echo the data in the order it comes from the database.  So not sure why you are not seeing unordered results.

If you run `pg_featureserv` in debug mode (`-d` or `--debug`) it will output the SQL queries generated by API requests.  Perhaps those queries will give an idea.  Also, you can run those queries directly and see if they exhibit the same behaviour.

**Comment by RoryMMMM** [comment]
I put the Featserv into debug mode and the query it is using (after some formatting) is
```

SELECT 
	ST_AsGeoJSON(geom) AS _geojson ,
	id,
	gid,
	canopy_mean,
	canopy_max,
	canopy_min,
	canopy_stddev,
	surface_mean,
	surface_max,
	surface_min,
	surface_stddev,
	built_area,
	asphalt_length,
	highway_length,
	pop_total 
FROM postgisftw.hex_environmental_features_30m     
LIMIT 1 OFFSET 10000;
```

Which seems fine. If I run this in PG Admin I get different results each time. So it seems this isn't a PG_Featureserv bug but rather something in my SQL or database.

**Comment by RoryMMMM** [comment]
I can't explain this...

I tried creating and querying some different versions of the view definition. I now have two windows open in PG Admin, both running the same SQL as above. The one window always returns the same row, the other always returns a different row...

The query plan for both are identical...

**Comment by pramsey** [comment]
Well as a general proposition, unless you impose an ORDER BY in your query, there is no guarantee that the system will return you answers in some particular order. As a specific observable behaviour though, it's true that they often do so, particularly on quiet systems.

**Comment by dr-jts** [comment]
`pg_featureserv` supports the `sortBy` query parameter. So you could add say `sortBy=id` to the query and see if that gives consistent results.

**Comment by RoryMMMM** [comment]
Ah, that makes sense. So I *should* be using a URL like:
`
http://localhost:9999/collections/postgisftw.hex_environmental_features_30m/items.json?limit=1&offset=10000&**sortby=gid**`

which is behaving correctly.

Which leads me to the next problem. I'm using the OWSLib as the OGC API client libary and it works well... except it doesn't seem to have a "sort by"
