### ISSUE TITLE
Only returns max 1000 features

### ISSUE THREAD

**Issue by tiboego** [CrunchyData/pg_featureserv#171]
Hi
I'm running pg-featureserv as docker image in Azure. I have a problem with the numbers of features returned by the server.

Even though I have set a max limit of 10.000:
https://[featureserv.azurewebsites.net/collections/dtu.llyn_parkering_plads/items.json?limit=10000](https://featureserv.azurewebsites.net/collections/dtu.llyn_parkering_plads/items.json?limit=10000)

Is it possible to set the LimitMax and LimitDefault in Enviroment Viriables ?

**Comment by JakobMiksch** [comment]
you can change these settings using environment variables and the config file https://github.com/CrunchyData/pg_featureserv/blob/a52f518950ed70f08e18d01d0a7ad2200dca709c/config/pg_featureserv.toml.example#L71-L75

**Comment by tiboego** [comment]
Great. Is it possible to overwrite config file with "LimitDefault" and "LimitMax" directly as Enviroment variables?

**Comment by JakobMiksch** [comment]
yes, that should be possible. It is described in the [README](https://github.com/CrunchyData/pg_featureserv?tab=readme-ov-file#configuration-using-environment-variables). Here is the relevant paragraph:

> Other parameters in the configuration file can be over-ridden in the environment. Prepend the upper-cased parameter name with PGFS_section_ to set the value.

**Comment by tiboego** [comment]
Great thanks!

**Comment by JakobMiksch** [comment]
@tiboego if your problem is solved, you can close the isse ;-)
