### ISSUE TITLE
cannot use openapi3.Info literal (type openapi3.Info) as type *openapi3.Info in field value

### ISSUE THREAD

**Issue by dBitech** [CrunchyData/pg_featureserv#22]
When attempting to go get the Repo, the error is gotten.

```
[user@getlost ~]$ go get -v github.com/CrunchyData/pg_featureserv
github.com/CrunchyData/pg_featureserv/api
# github.com/CrunchyData/pg_featureserv/api
go/src/github.com/CrunchyData/pg_featureserv/api/openapi.go:134:3: cannot use openapi3.Info literal (type openapi3.Info) as type *openapi3.Info in field value
[user@getlost ~]$
```

**Comment by dr-jts** [comment]
That's because pg_featureserv is currently using [v2.0](https://github.com/getkin/kin-openapi/releases/tag/v0.2.0) of that project, in which [Info is a struct, not a pointer](https://github.com/getkin/kin-openapi/blob/90a7df014b4e7699507bf82aa5601503a9ba85da/openapi3/swagger.go#L12).

I'm not sure why your Golang would not use this version of the codebase.  Could you be using an older version of Go that doesn't support modules?

**Comment by dBitech** [comment]
```
[darcy@getlost ~]$ go version
go version go1.13.7 freebsd/amd64
```

**Comment by dr-jts** [comment]
That's what I'm using as well.  Then not sure what to advise.  Perhaps you have to reset your Go repo copy of the openapi lib somehow?

**Comment by dBitech** [comment]
even more intresting, both og get and go build fail in the same way when run from the home dir. 
```
[darcy@getlost ~]$ go get github.com/CrunchyData/pg_featureserv
# github.com/CrunchyData/pg_featureserv/api
go/src/github.com/CrunchyData/pg_featureserv/api/openapi.go:134:3: cannot use openapi3.Info literal (type openapi3.Info) as type *openapi3.Info in field value
```
But if I change to the project dir, everything works fine.
```
[darcy@getlost ~]$ cd go/src/github.com/CrunchyData/pg_featureserv/
[darcy@getlost ~/go/src/github.com/CrunchyData/pg_featureserv]$ go get
[darcy@getlost ~/go/src/github.com/CrunchyData/pg_featureserv]$ go install
```

I'm not a go person at all, so maybe this is expected behavior,  I'm not sure.

**Comment by dr-jts** [comment]
> But if I change to the project dir, everything works fine.

Sounds good!  Closing this.
