### ISSUE TITLE
Comment on function dependency (ST_AsGeoJSON())

### ISSUE THREAD

**Issue by kbatuigas** [CrunchyData/pg_featureserv#25]
Similar to the note in pg_tileserv about ST_AsMVT() https://github.com/CrunchyData/pg_tileserv/blob/master/hugo/content/examples/_index.md - I can add this if it's the same

**Comment by dr-jts** [comment]
There is no dependency on latest version of `ST_AsGeoJSON`.  Should be good back to ver 2.0

**Comment by kbatuigas** [comment]
Thanks! I think this is all set.
