### ISSUE TITLE
Functions with no defaults cause panic

### ISSUE THREAD

**Issue by pramsey** [CrunchyData/pg_featureserv#31]
`runtime error: index out of range [0] with length 0`

Test function to demonstrate:
```sql
CREATE FUNCTION postgisftw.no_defaults(arg1 float8)
RETURNS TABLE(res1 text)
AS $$
  SELECT 'answer' AS res1;
$$ LANGUAGE 'sql'
STABLE STRICT;
```
Hit the metadata view: http://localhost:9000/functions/no_defaults.json

**Comment by dr-jts** [comment]
Should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/fedcbe3081b9dc88821e552c934a49745df1f33a
