### ISSUE TITLE
Schema name with uppercase letter causes "Unable to read data from"

### ISSUE THREAD

**Issue by andischi** [CrunchyData/pg_featureserv#49]
If a schema name includes uppercase letters the "Items" "View" and "JSON" dont work
e.g.:
https://../collections/Gebiete_Regionen.ak_aplenbogen_at_2016/items.json
causes:
"Unable to read data from: Gebiete_Regionen.ak_aplenbogen_at_2016"

while this works:
https://../collections/Gebiete_Regionen.ak_aplenbogen_at_2016.json

**Comment by dr-jts** [comment]
This is because the generated SQL does not have quoted names for queried tables.  Stand by for a fix!

**Comment by dr-jts** [comment]
Should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/19bdf944709b49c94ed2ab6f60b0269d56204b0a

@andischi Are you able to test and confirm?

**Comment by andischi** [comment]
@dr-jts Thanks! I will check it

**Comment by andischi** [comment]
@dr-jts Thanks again! It works
