### ISSUE TITLE
API to specify response properties

### ISSUE THREAD

**Issue by dr-jts** [CrunchyData/pg_featureserv#5]
OGC API has not yet specified this.

## Ideas
* STAC has an extension proposal [here](https://github.com/radiantearth/stac-spec/tree/master/api-spec/extensions/fields).  It allows specifying included and excluded properties.  Example: `fields=f1,f2,-f3,-f4`

## Design
* Syntax: `properties=propa,propb,...`
* supported for resources `items` and `items/id`
* in order to ensure valid GeoJSON, properties for ID and geometry are always included 
  * Would be nice to be able to skip geometry if not needed.  Can GeoJSON `geometry` be empty?
* for now only support inclusion, not exclusion
* invalid property names are ignored, rather than causing an error
* If the name changes in the standard it is easy to add or change

**Comment by dr-jts** [comment]
Now implemented.

**Comment by KiwiKilian** [comment]
> Would be nice to be able to skip geometry if not needed. Can GeoJSON geometry be empty?

@dr-jts because I couldn't find anything, may I ask: is there a way to get features without the geometries? Using `properties=id` still includes the `geometry`.
