### ISSUE TITLE
basic https support

### ISSUE THREAD

**Issue by smnorris** [CrunchyData/pg_featureserv#50]
Can this be applied here? https://github.com/CrunchyData/pg_tileserv/issues/7

**Comment by smnorris** [comment]
I seem to have figured out a way around it in my web server config.

**Comment by pramsey** [comment]
This is a reasonable feature request. While it's easy enough to reverse proxy an HTTPS front-end on an HTTP service, it's "standard practice" now to also ensure all intra-network connections are also HTTPS, so every service needs to be able to do it.

**Comment by dr-jts** [comment]
@smnorris Just committed support for HTTPS.  Are you able to test this out?

See [here](https://github.com/CrunchyData/pg_featureserv/blob/master/config/pg_featureserv.toml.example#L7-L12) for required configuration.

**Comment by smnorris** [comment]
Can't test immediately but should be able to try out this and the other fixes in the next week or so.

**Comment by smnorris** [comment]
"Next week or so" turned into more than 8 months later... but I have finally upgraded to the latest pg_featureserv and this does work just fine - thanks @dr-jts
