### ISSUE TITLE
Unknown type error for ltree column type

### ISSUE THREAD

**Issue by smnorris** [CrunchyData/pg_featureserv#51]
I'm getting this error at https://www.hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_assessment_watersheds_poly.html

```
INFO[0078] [::1]:64762 GET /collections/whse_basemapping.fwa_assessment_watersheds_poly/items.json
WARN[0078] Error scanning row for Feature: Unknown type
WARN[0078] Error scanning rows for Features: Unknown type
INFO[0078] JSON encoding error: json: error calling MarshalJSON for type *json.RawMessage: unexpected end of JSON input
```

The only non-standard type in the table is `ltree`, the columns are generated like this:
```
ALTER TABLE whse_basemapping.fwa_assessment_watersheds_poly ADD COLUMN wscode_ltree ltree
  GENERATED ALWAYS AS (REPLACE(REPLACE(fwa_watershed_code, '-000000', ''), '-', '.')::ltree) STORED;
```

The collection page does show ltree types as strings though:
![Screen Shot 2020-07-10 at 3 39 11 PM](https://user-images.githubusercontent.com/1323293/87208480-b63bb900-c2c3-11ea-8c1d-e1e93606ef9a.png)

**Comment by dr-jts** [comment]
@smnorris Is this fixed?

**Comment by smnorris** [comment]
Yes, thanks. @stephenhillier 's fix worked for me - the ltree columns listed at the bottom show up as strings:
https://www.hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_assessment_watersheds_poly.html

**Comment by dr-jts** [comment]
Great, will close this ticket.
