### ISSUE TITLE
Table with field of type hstore causes warnings and 0 records output

### ISSUE THREAD

**Issue by spatial-intelligence** [CrunchyData/pg_featureserv#53]
Trying to show a table which includes a field of type hstore and results in 0 records ouptut.
Guessing the hstore curly brackets mess up the JSON output.

WARN[0265] Error scanning row for Feature: Unknown type 
WARN[0265] Error scanning rows for Features: Unknown type 
INFO[0265] JSON encoding error: json: error calling MarshalJSON for type *json.RawMessage: unexpected end of JSON input

**Comment by dr-jts** [comment]
What would you expect to see as a JSON representation?

As a workaround, you can make a view which does not contain that column (or possibly extracts any desired values from it).

**Comment by spatial-intelligence** [comment]
I ran thru an example fine then switched to trying some OSM data with multiple geometry fields in different coordinate systems, and it didn’t work. It took a little while to figure why. I did use a VIEW to get around it. It would be good to flag the reason in the warning, possibly a field type check to report hstore isn’t supported? Alternatively cast it all to text with brackets removed? For a while I thought it was due to having multiple geometry fields.

**Comment by stephenhillier** [comment]
This sounds similar to #51 just with a different type ; I just tested PR #52 with an hstore column and it works with the test data I used.

**Comment by dr-jts** [comment]
Can you test and see if this problem has been fixed by PR #52?

**Comment by spatial-intelligence** [comment]
Yep, that's all good now with the hstore field.
Thanks.
