### ISSUE TITLE
Feature collection Extent property is not populated

### ISSUE THREAD

**Issue by smnorris** [CrunchyData/pg_featureserv#54]
pg_featureserv reports `Extent` = 0,0,0,0  for all collections I'm serving.
eg: https://www.hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_glaciers_poly.html

I've poked around in https://github.com/CrunchyData/pg_featureserv/tree/master/data and can't tell where the server is pulling the values from. Maybe this is a just a database configuration I'm missing?

**Comment by pramsey** [comment]
Hm, I vaguely recall using estimate_extent, which means you need a spatial index in place, and run 'analyze' on the database. That's what I thing tileserv needs.

**Comment by smnorris** [comment]
Yep, I can see that in tileserv - but I can't see any similar sql in featureserv. https://github.com/CrunchyData/pg_tileserv/blob/858c299bc83c1c7fbcdc363b3ce6d958b1438b67/layer_table.go#L275

**Comment by dr-jts** [comment]
That functionality needs to be ported from pg_tileserv.

**Comment by mstefarov** [comment]
One more note: currently the structure of the `extent` object and the formatting of `crs` parameter are not standards-compliant.

Example `extent` served by pg_featureserv:
```json
"extent": {
	"crs": "EPSG:3005",
	"bbox": [0, 0, 0, 0]
}
```

Example of compliant `extent` object:
```json
"extent": {
	"spatial": {
		"crs": "http://www.opengis.net/def/crs/EPSG/0/3005",
		"bbox": [0, 0, 0, 0]
	}
}
```

References:
- OpenAPI schema for `extent`: https://github.com/opengeospatial/ogcapi-features/blob/master/core/openapi/schemas/extent.yaml (part of _OGC API - Features - Part 1: Core_)
- Requirements/recommendations for CRS format: http://docs.opengeospatial.org/is/18-058/18-058.html#crs-overview (part of _OGC API - Features - Part 2: Coordinate Reference Systems by Reference_)

**Comment by dr-jts** [comment]
Done in https://github.com/CrunchyData/pg_featureserv/commit/17747d7d88ac91e239676299e632cd5bf91b5af3.

Can you test?

**Comment by dr-jts** [comment]
> One more note: currently the structure of the `extent` object and the formatting of `crs` parameter are not standards-compliant.

@mstefarov  Good point, thanks.  I will look into this.  You might want to open a different ticket to track this.

**Comment by dr-jts** [comment]
> the structure of the extent object and the formatting of crs parameter are not standards-compliant.

@mstefarov fixed in https://github.com/CrunchyData/pg_featureserv/commit/b9ca9ca94d5b1e49922f185e18f2441e8ca56ce3.  Are you able t try and confirm?

**Comment by dr-jts** [comment]
@smnorris can you confirm this is fixed?

**Comment by smnorris** [comment]
It looks fine on the featureserv default web interface to my local db.  My only comment is that is a lot of decimal places of precision...
```
Extent	Lon/Lat Min: -127.81736627296681, 48.92185609542121 Max: -112.39803524683387, 55.424095307814035
```
