### ISSUE TITLE
support for materialized view

### ISSUE THREAD

**Issue by elwoodhouse** [CrunchyData/pg_featureserv#56]
Hi,

I am trying out this service and I am impressed with the speed in which it can be setup. The first thing I tried was to expose a materialized view and it seems that this is not currently supported as the simple HTML user interface doesn't list my materialized view. Is that right? 

If so could this please be put on the enhancement list?

For reference the pg_tileserv service does pick up the materialized view and it is using the same database connection as pg_featureserv so I don't think it's a permission issue.

Thanks.

**Comment by dr-jts** [comment]
Yes, this was added to pg_tileserv recently ([PR](https://github.com/CrunchyData/pg_tileserv/pull/51)).  It's a simple fix.
