### ISSUE TITLE
Make No Data error more informative. 

### ISSUE THREAD

**Issue by mikefedak** [CrunchyData/pg_featureserv#59]
I have been experimenting with publishing functions with pg_featureserv and have noticed that if a query returns zero features, the error returned when zero features are returned by the query is "[ErrMsgDataRead](https://github.com/CrunchyData/pg_featureserv/blob/702a52365d697fd8e738e94f6a944f44a2b3d995/api/api.go#L69)". This is a bit confusing because to me "Unable to read data from" implies (to me anyways) that the table could not be accessed. I have been trying to handle a null result in the function using a conditional statement but is there any chance to make the error message more informative?

**Comment by dr-jts** [comment]
Good idea to differentiate a DB error from no features found. It's easy to change the error message.

Not actually sure why this is considered an error - it would be much better if it wasn't, since returning no features seems like a reasonable thing to handle.

**Comment by dr-jts** [comment]
@mikefedak I am considering making a change that for queries with no result will return an empty FeatureCollection (or JSON array in the case of a non-spatial function).  This seems like better behaviour, instead of returning an error.

If I push this are you able to build and test?

**Comment by mikefedak** [comment]
Yes, gladly.

**Comment by dr-jts** [comment]
@mikefedak I have committed a fix to return empty collections/arrays instead of error.  Please let us know if that works for you.

**Comment by mikefedak** [comment]
Great, I will build the new version and test today.

**Comment by mikefedak** [comment]
Tested. Rather than the error, it returns an empty json []. Great, thank you!

**Comment by dr-jts** [comment]
Great, thanks for confirming.
