### ISSUE TITLE
How to change default url for pg_featureserv

### ISSUE THREAD

**Issue by Parthiv20** [CrunchyData/pg_featureserv#61]
* I would like to change default url from `localhost:9000` to `localhost:9000/api/pg-featureserv`.
* I tried by changing `config/pg_featureserv.toml` file. Set UrlBase parameter to  `https://example.in/api/pg-featureserv` and restarted the server with command `./pg_featureserv --config ./config/pg_featureserv.toml` 
* The server still runs on `localhost:9000`.

**Comment by dr-jts** [comment]
This is what people normally use a proxy server to do.  The `UrlBase` config is currently only used to make the service conform to the proxy in front of it.

That said, if there is a way to do this easily internally to the service then that could be a nice addition.

**Comment by NasNasingud** [comment]
In pg_tileserv, there is a config parameter available called `BasePath`, in addition to `UrlBase`. It would be very helpful for proxy server environments if the `BasePath` parameter could also be implemented in pg_featureserv with the same functionality. Maybe this could fix the issue mentioned by Parthiv20.

**Comment by dr-jts** [comment]
Yes, that's a good enhancement.  Will work on implementing this soon.
