### ISSUE TITLE
Function requests do not respect offset parameter

### ISSUE THREAD

**Issue by elwoodhouse** [CrunchyData/pg_featureserv#65]
Hi, is there some config or function setting that I need to make to get the offset query parameter to work?

I've followed the user guide in creating the function and that is able to retrieve the data successfully with the limit query parameter working, but when I try to add the offset query parameter to get paging working it doesn't change the resulting data.

![image](https://user-images.githubusercontent.com/38488541/107103859-52866800-6873-11eb-95c7-d560d86b30ea.png)

![image](https://user-images.githubusercontent.com/38488541/107103904-8d889b80-6873-11eb-9455-c8dd697aad65.png)

**Comment by dr-jts** [comment]
This is a limitation in the current implementation.  The function query is not adding the `OFFSET` clause.  It's an easy fix - should be done soon.

**Comment by dr-jts** [comment]
Should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/b006ce171e8649d83c9bd9f62a9f2ee4e9d38228.

@elwoodhouse are you able to test?

**Comment by elwoodhouse** [comment]
I haven't run a build before but the steps look pretty straight forward so I can have a go on the weekend.

**Comment by elwoodhouse** [comment]
Confirmed as working.

Thanks.
