### ISSUE TITLE
Support for foreign tables?

### ISSUE THREAD

**Issue by Jnb2387** [CrunchyData/pg_featureserv#67]
is it possible to have pg_featureserv read foreign tables? I have tried a couple different fdw's (postgres_fdw, ogr_fdw) and have not been able to view the foreign table unless I create an actual table or materialized view.
The foreign table has the proper type and SRID geom Geometry(Point, 4326).

**Comment by dr-jts** [comment]
I just added support for foreign and partitioned tables.  Can you try out the master version?

**Comment by Jnb2387** [comment]
Awesome! works great now. Thank you.
