### ISSUE TITLE
Hardcoded version number in Hugo content

### ISSUE THREAD

**Issue by crunchyjoea** [CrunchyData/pg_featureserv#68]
pg_featureserv/hugo/content/_index.md has hardcoded reference to version 1.1. 
 

> 
"This is the documentation for `pg_featureserv` version 1.1."

Would it be possible to either update this reference with every tag, or remove the version here?

Thanks!

**Comment by dr-jts** [comment]
Fixed, by removing the version number.

Not sure how to add a dynamically-updated version number, but that would be nice.
