### ISSUE TITLE
Description on a database table is not used in the HTML UI page

### ISSUE THREAD

**Issue by petergarnaes** [CrunchyData/pg_featureserv#70]
The description of a collection in the UI seems to be pulled from the last element of the table column descriptions. This is illustrated in the image below.

![Screenshot_2021-04-08 pg-featureserv](https://user-images.githubusercontent.com/1044051/114020797-410c0d00-9870-11eb-8098-60d54df750c6.png)

This applies even when there exists a description on the table itself.

I am running the 'Quick Start' setup but with the schema name `ogc_api` instead of `ne`. I have modified the descriptions with the following psql commands:
```
comment on table ogc_api.countries is 'Set of countries from natural earth';
comment on column ogc_api.countries.gid is 'Unique identifier';
comment on column ogc_api.countries.name is 'Official name of the country, which is in the local official language';
comment on column ogc_api.countries.name_long is 'Official country name with extra titles like Kingdom of ... etc.';
```

## Expected behaviuor

I would expect the description on the table from which the collection is derived to be used as the description of the collection. I have attached a screenshot below to illustrate, its modified HTML and not an example showing it working.

![Screenshot_2021-04-08 pg-featureserv(1)](https://user-images.githubusercontent.com/1044051/114021808-63525a80-9871-11eb-9398-960eecf2237e.png)

**Comment by petergarnaes** [comment]
It seems to apply to `/collections/{collectionId}` endpoint as well

**Comment by dr-jts** [comment]
This should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/9f53d32a190bd0b20248e66f1e27c68fac97131f

@petergarnaes can you verify?
