### ISSUE TITLE
Conformance links all return "Not found"

### ISSUE THREAD

**Issue by mcarson75** [CrunchyData/pg_featureserv#73]
The three links specified for conformance in `internal/api.go` line 459

```
var conformance = Conformance{
	ConformsTo: []string{
		"http://www.opengis.net/spec/wfs-1/3.0/req/core",
		"http://www.opengis.net/spec/wfs-1/3.0/req/geojson",
		"http://www.opengis.net/spec/wfs-1/3.0/req/html",
	},
}
```
all return "Not found" when clicked.

**Comment by dr-jts** [comment]
The conformance classes have been updated in https://github.com/CrunchyData/pg_featureserv/commit/7482c3666e461287d8ce1daf3a890e5ca112c1c0.

Note that the links to standards other than _OGCAPI-Features_ still return "Not found".  This is because the corresponding OGC standards are still in draft.
