### ISSUE TITLE
Where do the functions come from?

### ISSUE THREAD

**Issue by leeberryman** [CrunchyData/pg_featureserv#74]
I have shared the functions in the underlying db with the user that is running pg_featureserv, but the functions do not persist to the API.  Where in the code do these come from and what is logic that I should step back through to find where the functions are blocked?

**Comment by dr-jts** [comment]
Are your functions in the `postgisftw` schema?  Currently that is the only place that functions are sourced from (to avoid exposing too many functions).  See the _User Guide_ [**Functions**](https://access.crunchydata.com/documentation/pg_featureserv/latest/usage/functions/) section.

See also #21 for future ideas about some more flexibility to this.

**Comment by leeberryman** [comment]
Thanks.  Looks like all the postgis functions are in the public schema.  I'll migrate them.

**Comment by dr-jts** [comment]
It sounds like you might be trying to expose PostGIS functions?  That's not actually the primary use case for the published functions, although they can be used that way, by providing the inputs as request parameters with WKT or WKB values.

You might also have a look at the (so far undocumented) capability of running geometry transforms in queries against collections or functions - see [this issue comment](https://github.com/CrunchyData/pg_featureserv/issues/75#issuecomment-885798263).
