### ISSUE TITLE
Add geometry simplification to requests?

### ISSUE THREAD

**Issue by rowanwins** [CrunchyData/pg_featureserv#75]
@dr-jts I'm just checking out this repo after successfully using pg_tileserv for a while.

I'm just trying to see if I can request simplified geometries, over in #2 you mention
>  simplify=TOLERANCE parameter to run geometry simplification
  can be done with transform=simplify...

Do you have a more fleshed out example of what that might look like?
`./collections/whatever/items.json?limit=1&transform=simplify...`

The doco is a little sparse on how to add arguments, or maybe the comment above is a little out of date.

I'm planning on putting together a little plugin for maplibre-gl/mapbox-gl for consuming WFS2 via tiled requests, and I'd ideally like to include some geometry simplification when zoomed out. I've recently put together a [similar lib](https://rowanwins.github.io/mapbox-gl-arcgis-featureserver/) for arcgis feature servers.

Cheers,
Rowan

**Comment by rowanwins** [comment]
Or maybe your comment that "it can be done with" means that it could in theory be supported, rather than it can already be done...

**Comment by dr-jts** [comment]
Hi, Rowan, great that you're trying out `pg_featureserv`.

> I'm just trying to see if I can request simplified geometries
> 
> Do you have a more fleshed out example of what that might look like?
> `./collections/whatever/items.json?limit=1&transform=simplify...`

Yes, the doco is a bit sparse for this feature right now - I am working on fixing that!   Including a blog post with lots of examples, soon.

This functionality does work.  You need to ensure that you have the [transform whitelist](https://github.com/CrunchyData/pg_featureserv/blob/master/config/pg_featureserv.toml.example#L36) in the config file configured to include the `ST_Simplify` function:
```
TransformFunctions = [ "ST_Simplify" ]
```
Then you can invoke the transform function using the request parameter `transform=simplify,0.1`:
```
http://localhost:9000/collections/ne.admin_0_countries/items.html?transform=simplify,0.1
```
Here's an image showing the effect:
![image](https://user-images.githubusercontent.com/3529053/126820822-1b913508-eb55-4742-b111-9b493620d649.png)

Be aware that I just noticed a bug, in that if the transformed geometry is `NULL`, then the request will fail.  I'll work on fixing that ASAP.

And of course you might want to use [`ST_SimplifyPreserveTopology`](https://postgis.net/docs/manual-3.1/ST_SimplifyPreserveTopology.html) if you need to have valid polygons output.

Let me know how it goes...

**Comment by rowanwins** [comment]
Ahhhh the old comma trick, why didn't I think of that! I had found the configuration file bit to support the function.

I'll keep you posted on progress of my lib. 

Thanks @dr-jts
