### ISSUE TITLE
documentation - sortBy vs orderBy

### ISSUE THREAD

**Issue by smnorris** [CrunchyData/pg_featureserv#78]
Current feature query docs show param `orderBy` but it looks like the current release uses `sortBy`?
https://access.crunchydata.com/documentation/pg_featureserv/latest/usage/query_data/

**Comment by dr-jts** [comment]
Yes, the doc release is lagging the codebase.  

`sortBy` is now in the OGC standard, so `pg_featureserv` has switched to that syntax.  `orderBy` is still available, but deprecated.

**Comment by smnorris** [comment]
Thanks Martin.  Not important but I am pretty sure I'm using v1.2.0 release and `orderBy` is ignored.
