### ISSUE TITLE
Query OFFSET value does not match request parameter value

### ISSUE THREAD

**Issue by smnorris** [CrunchyData/pg_featureserv#79]
Trying to page through a large set of features (FWA streams), using offset and sortby params, the offset param seems to be capped by the server at 10k:

pg_featurserv log showing the request and response - the offsets do not match:
```
INFO[1020] 127.0.0.1:36904 GET /collections/whse_basemapping.fwa_stream_networks_sp/items.json?sortBy=linear_feature_id&limit=1&offset=11000

DEBU[1020] Features query: 
SELECT ST_AsGeoJSON( ST_Transform( "geom", 4326)  ) AS _geojson , 
"linear_feature_id","watershed_group_id".....<etc etc>
FROM "whse_basemapping"."fwa_stream_networks_sp"   ORDER BY "linear_feature_id"   
LIMIT 1 OFFSET 10000;
DEBU[1020] Database query result: 1 rows in 427.282033ms
DEBU[1020] ---- Request complete in 431.749204ms
```

Perhaps `LimitMax` in my config below is applying to offset, but how would paging work if this is the case?

```
[Paging]
# The default number of features in a response
LimitDefault = 10000
# Max number of features in a response
LimitMax = 10000
```
https://github.com/poissonconsulting/fwapgr/issues/40#issuecomment-914440713

**Comment by dr-jts** [comment]
I see this too.   Will look into it ASAP.

**Comment by dr-jts** [comment]
Was a small bug.  Should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/8e9df4956df38d1b24af5ad07b426ead3bca66f5

**Comment by smnorris** [comment]
Thanks for the quick fix! 

I'm going to add a record count function to the db as per our earlier discussion so we'll probably test pagination out a bit more. https://github.com/poissonconsulting/fwapgr/issues/47

**Comment by dr-jts** [comment]
Great, let us know how it goes.

As per previous discussions paging is not fully built out in pg_fs, but there are some slightly hacky workarounds.  It would be nice to get this working in a reasonable way (simple AND performant - if that's possible!).  It's pretty high on the ToDo list, so feedback and ideas are welcome.

**Comment by smnorris** [comment]
I'm working through it here. Probably going with something like a `postgisftw.record_count` meta table - https://github.com/smnorris/fwapg/issues/56
