### ISSUE TITLE
OGI limit parameter not returning more than 1000 features

### ISSUE THREAD

**Issue by sgwethan8** [CrunchyData/pg_featureserv#89]
![image](https://user-images.githubusercontent.com/59086795/139660509-28c4c62f-4c32-49d4-ad28-2ca2cb08e61e.png)

Seems that no matter what number of features is specified, if the limit is set to a number greater than 1000 then only 1000 are returned.

![image](https://user-images.githubusercontent.com/59086795/139660525-c948e5c1-0f08-4bba-84cf-5a29d2ee5382.png)

**Comment by dBitech** [comment]
check what LimitMax is set to in your [configuration file](https://github.com/CrunchyData/pg_featureserv/blob/4a789b451bc74eb241f4bb7d00033b949d51d5ca/config/pg_featureserv.toml.example#L64).

**Comment by sgwethan8** [comment]
> check what [LimitMax](https://github.com/CrunchyData/pg_featureserv/blob/master/hugo/content/installation/configuration.md#limitmax) is set to in your [configuration file](https://github.com/CrunchyData/pg_featureserv/blob/4a789b451bc74eb241f4bb7d00033b949d51d5ca/config/pg_featureserv.toml.example#L64). the Example file has this set to 1000,

Am I missing something however, because the Example file is set to 10000 as the default?

**Comment by sgwethan8** [comment]
I'm closing this issue as it's no longer a problem.. simple solution for anyone looking here is to specify a volume of type bind on a docker compose file or docker pull and then for the source parameter point docker to your custom config file
