### ISSUE TITLE
Map view doesn't work on the latest master branch

### ISSUE THREAD

**Issue by sanak** [CrunchyData/pg_featureserv#92]
I am trying the following steps on the latest master branch,
https://access.crunchydata.com/documentation/pg_featureserv/1.2.0/examples/ex_query_data/
> The query can also be returned as a map view in the web UI:
> ```
> http://localhost:9000/collections/ne.countries/items.html
> ```

but map view doesn't work by the following error.
![issue-loader-failed1](https://user-images.githubusercontent.com/629923/145718122-bf893f52-e3c5-4533-8d3a-ad425c8c73ad.png)
![issue-loader-failed2](https://user-images.githubusercontent.com/629923/145718126-8486a96c-d70d-4b1a-ab6f-7dbc61069d7f.png)

I noticed that base url and path are concatenated without `/`, and after resetting the commits before #88 PR, the error didn't happen, so I think that #88 needs more fix on the web UI side.
```bash
$ git reset --hard 4a789b451bc74eb241f4bb7d00033b949d51d5ca
```

**Comment by dr-jts** [comment]
This should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/910ca4dd720500362d2d36c927a2b0771007c478.

@sanak are you able to test this and confirm?

**Comment by sanak** [comment]
Okay, thanks.
I will check it tonight.

**Comment by sanak** [comment]
@dr-jts Thanks for quick fix!
I confirmed that it works now. 😄

**Comment by dr-jts** [comment]
Excellent!  Thanks for confirming.  I'll close this issue now.
