### ISSUE TITLE
Config parameter TableIncludes is set but not working

### ISSUE THREAD

**Issue by arashgh-gh** [CrunchyData/pg_featureserv#95]
I used TableInlcudes for just one schema in the cofing toml but my application still lists all of the tables and schemata in my database under collections. 

I am using the docker image with pg_featureserv (V 1.1).
  
time="2021-12-21T12:09:51Z" level=info msg="----  pg_featureserv - Version 1.1 ----------\n"
time="2021-12-21T12:09:51Z" level=info msg="Using config file: pg_featureserv"
time="2021-12-21T12:09:51Z" level=info msg="Using database connection info from config file"

**Comment by dr-jts** [comment]
That version looks too old to have `TableIncludes`.   Can you upgrade to latest?

**Comment by arashgh-gh** [comment]
Upgrading to the latest version solved the problem. Thanks.
