### ISSUE TITLE
Return Error or Warning Message

### ISSUE THREAD

**Issue by Jnb2387** [CrunchyData/pg_featureserv#96]
I am able to view the ERROR code from my plpgsql function on the server, but is it possible to return the message from postgres in the response? I am not sure if this was returned before #59 , the response empty data array is useful but even with a raise exception its hard to know the query didnt run successfully.

**Comment by dr-jts** [comment]
My thinking was that it is better to not return the internal errors via the API, since that might leak unwanted information.  They should be logged, however.  Are you not seeing this?

**Comment by Jnb2387** [comment]
I see them logged on the server, I may just be forcing it to work but I was trying to test out and create an update or rather upsert function and send the parameters via pg_featureserv, which does work fine but if I create an exception in the function it still will return with a 200 OK response. This may be fine as the data array returned will still be empty and I can error out on that.

**Comment by dr-jts** [comment]
Right, I just noticed that myself.  That does seem like a design flaw.  The error should be indicated in the response somehow, even if it doesn't contain the internal error message.  I will have to check and see if there is a standard way to encode an error message in the response document.

At least the HTTP response code should be set to indicate an error.  Perhaps 500, or else 404?

**Comment by dr-jts** [comment]
It turns out that this is in fact a bug.  This particular error was not being passed back up the function chain.  This is now fixed in https://github.com/CrunchyData/pg_featureserv/commit/da64e208119081c566548e8258ddcfa6fce8b23a.

I'm not sure the reponse body is appropriate, however - it is HTML, rather than JSON.  This needs looking into.  The HTTP Status Code is correct however - it is 500.

**Comment by dr-jts** [comment]
@Jnb2387 can this issue be closed?

**Comment by Jnb2387** [comment]
Yes sorry. PG_Featureserv just keeps getting better and better! Thanks @dr-jts
